version: "3.1"
services:
    object-store-orchestrator:
        restart: always
        build: ./
        image: orchestrator-service
        ports:
            - 8080:8080
networks:
    default:
        external:
            name: network-object-store